export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const UPDATE_FEILD_VOLUME = 'UPDATE_FEILD_VOLUME';
export const UPDATE_IS_UNLOCKED = 'UPDATE_IS_UNLOCKED';
export const UPDATE_HOSTNAME = 'UPDATE_HOSTNAME';
